// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260702093204_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Alphabets.AlphabetLetter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ExampleEmoji")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("ExampleWord")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("LowerCase")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Sound")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("UpperCase")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder")
                        .IsUnique();

                    b.ToTable("alphabet_letters", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1ea0000-0000-4000-8000-000000000001"),
                            DisplayOrder = 1,
                            ExampleEmoji = "👕",
                            ExampleWord = "áo",
                            LowerCase = "a",
                            Name = "a",
                            Sound = "a",
                            UpperCase = "A"
                        },
                        new
                        {
                            Id = new Guid("d1ea0000-0000-4000-8000-000000000002"),
                            DisplayOrder = 2,
                            ExampleEmoji = "🍚",
                            ExampleWord = "ăn",
                            LowerCase = "ă",
                            Name = "á",
                            Sound = "á",
                            UpperCase = "Ă"
                        },
                        new
                        {
                            Id = new Guid("d1ea0000-0000-4000-8000-000000000003"),
                            DisplayOrder = 3,
                            ExampleEmoji = "🫖",
                            ExampleWord = "ấm",
                            LowerCase = "â",
                            Name = "ớ",
                            Sound = "ớ",
                            UpperCase = "Â"
                        },
                        new
                        {
                            Id = new Guid("d1ea0000-0000-4000-8000-000000000004"),
                            DisplayOrder = 4,
                            ExampleEmoji = "🐄",
                            ExampleWord = "bò",
                            LowerCase = "b",
                            Name = "bê",
                            Sound = "bờ",
                            UpperCase = "B"
                        },
                        new
                        {
                            Id = new Guid("d1ea0000-0000-4000-8000-000000000005"),
                            DisplayOrder = 5,
                            ExampleEmoji = "🐟",
                            ExampleWord = "cá",
                            LowerCase = "c",
                            Name = "xê",
                            Sound = "cờ",
                            UpperCase = "C"
                        },
                        new
                        {
                            Id = new Guid("d1ea0000-0000-4000-8000-000000000006"),
                            DisplayOrder = 6,
                            ExampleEmoji = "🩴",
                            ExampleWord = "dép",
                            LowerCase = "d",
                            Name = "dê",
                            Sound = "dờ",
                            UpperCase = "D"
                        },
                        new
                        {
                            Id = new Guid("d1ea0000-0000-4000-8000-000000000007"),
                            DisplayOrder = 7,
                            ExampleEmoji = "💡",
                            ExampleWord = "đèn",
                            LowerCase = "đ",
                            Name = "đê",
                            Sound = "đờ",
                            UpperCase = "Đ"
                        },
                        new
                        {
                            Id = new Guid("d1ea0000-0000-4000-8000-000000000008"),
                            DisplayOrder = 8,
                            ExampleEmoji = "👶",
                            ExampleWord = "em bé",
                            LowerCase = "e",
                            Name = "e",
                            Sound = "e",
                            UpperCase = "E"
                        },
                        new
                        {
                            Id = new Guid("d1ea0000-0000-4000-8000-000000000009"),
                            DisplayOrder = 9,
                            ExampleEmoji = "🐸",
                            ExampleWord = "ếch",
                            LowerCase = "ê",
                            Name = "ê",
                            Sound = "ê",
                            UpperCase = "Ê"
                        },
                        new
                        {
                            Id = new Guid("d1ea0000-0000-4000-8000-00000000000a"),
                            DisplayOrder = 10,
                            ExampleEmoji = "🐔",
                            ExampleWord = "gà",
                            LowerCase = "g",
                            Name = "giê",
                            Sound = "gờ",
                            UpperCase = "G"
                        },
                        new
                        {
                            Id = new Guid("d1ea0000-0000-4000-8000-00000000000b"),
                            DisplayOrder = 11,
                            ExampleEmoji = "🌸",
                            ExampleWord = "hoa",
                            LowerCase = "h",
                            Name = "hát",
                            Sound = "hờ",
                            UpperCase = "H"
                        },
                        new
                        {
                            Id = new Guid("d1ea0000-0000-4000-8000-00000000000c"),
                            DisplayOrder = 12,
                            ExampleEmoji = "🤫",
                            ExampleWord = "im lặng",
                            LowerCase = "i",
                            Name = "i",
                            Sound = "i",
                            UpperCase = "I"
                        },
                        new
                        {
                            Id = new Guid("d1ea0000-0000-4000-8000-00000000000d"),
                            DisplayOrder = 13,
                            ExampleEmoji = "🍬",
                            ExampleWord = "kẹo",
                            LowerCase = "k",
                            Name = "ca",
                            Sound = "cờ",
                            UpperCase = "K"
                        },
                        new
                        {
                            Id = new Guid("d1ea0000-0000-4000-8000-00000000000e"),
                            DisplayOrder = 14,
                            ExampleEmoji = "🍃",
                            ExampleWord = "lá",
                            LowerCase = "l",
                            Name = "e-lờ",
                            Sound = "lờ",
                            UpperCase = "L"
                        },
                        new
                        {
                            Id = new Guid("d1ea0000-0000-4000-8000-00000000000f"),
                            DisplayOrder = 15,
                            ExampleEmoji = "🐱",
                            ExampleWord = "mèo",
                            LowerCase = "m",
                            Name = "em-mờ",
                            Sound = "mờ",
                            UpperCase = "M"
                        },
                        new
                        {
                            Id = new Guid("d1ea0000-0000-4000-8000-000000000010"),
                            DisplayOrder = 16,
                            ExampleEmoji = "👒",
                            ExampleWord = "nón",
                            LowerCase = "n",
                            Name = "en-nờ",
                            Sound = "nờ",
                            UpperCase = "N"
                        },
                        new
                        {
                            Id = new Guid("d1ea0000-0000-4000-8000-000000000011"),
                            DisplayOrder = 17,
                            ExampleEmoji = "🐝",
                            ExampleWord = "ong",
                            LowerCase = "o",
                            Name = "o",
                            Sound = "o",
                            UpperCase = "O"
                        },
                        new
                        {
                            Id = new Guid("d1ea0000-0000-4000-8000-000000000012"),
                            DisplayOrder = 18,
                            ExampleEmoji = "🚗",
                            ExampleWord = "ô tô",
                            LowerCase = "ô",
                            Name = "ô",
                            Sound = "ô",
                            UpperCase = "Ô"
                        },
                        new
                        {
                            Id = new Guid("d1ea0000-0000-4000-8000-000000000013"),
                            DisplayOrder = 19,
                            ExampleEmoji = "🍑",
                            ExampleWord = "quả mơ",
                            LowerCase = "ơ",
                            Name = "ơ",
                            Sound = "ơ",
                            UpperCase = "Ơ"
                        },
                        new
                        {
                            Id = new Guid("d1ea0000-0000-4000-8000-000000000014"),
                            DisplayOrder = 20,
                            ExampleEmoji = "🔋",
                            ExampleWord = "pin",
                            LowerCase = "p",
                            Name = "pê",
                            Sound = "pờ",
                            UpperCase = "P"
                        },
                        new
                        {
                            Id = new Guid("d1ea0000-0000-4000-8000-000000000015"),
                            DisplayOrder = 21,
                            ExampleEmoji = "🎁",
                            ExampleWord = "quà",
                            LowerCase = "q",
                            Name = "quy",
                            Sound = "quờ",
                            UpperCase = "Q"
                        },
                        new
                        {
                            Id = new Guid("d1ea0000-0000-4000-8000-000000000016"),
                            DisplayOrder = 22,
                            ExampleEmoji = "🐢",
                            ExampleWord = "rùa",
                            LowerCase = "r",
                            Name = "e-rờ",
                            Sound = "rờ",
                            UpperCase = "R"
                        },
                        new
                        {
                            Id = new Guid("d1ea0000-0000-4000-8000-000000000017"),
                            DisplayOrder = 23,
                            ExampleEmoji = "⭐",
                            ExampleWord = "sao",
                            LowerCase = "s",
                            Name = "ét-sì",
                            Sound = "sờ",
                            UpperCase = "S"
                        },
                        new
                        {
                            Id = new Guid("d1ea0000-0000-4000-8000-000000000018"),
                            DisplayOrder = 24,
                            ExampleEmoji = "🍎",
                            ExampleWord = "táo",
                            LowerCase = "t",
                            Name = "tê",
                            Sound = "tờ",
                            UpperCase = "T"
                        },
                        new
                        {
                            Id = new Guid("d1ea0000-0000-4000-8000-000000000019"),
                            DisplayOrder = 25,
                            ExampleEmoji = "🥤",
                            ExampleWord = "uống nước",
                            LowerCase = "u",
                            Name = "u",
                            Sound = "u",
                            UpperCase = "U"
                        },
                        new
                        {
                            Id = new Guid("d1ea0000-0000-4000-8000-00000000001a"),
                            DisplayOrder = 26,
                            ExampleEmoji = "🦁",
                            ExampleWord = "sư tử",
                            LowerCase = "ư",
                            Name = "ư",
                            Sound = "ư",
                            UpperCase = "Ư"
                        },
                        new
                        {
                            Id = new Guid("d1ea0000-0000-4000-8000-00000000001b"),
                            DisplayOrder = 27,
                            ExampleEmoji = "🐘",
                            ExampleWord = "voi",
                            LowerCase = "v",
                            Name = "vê",
                            Sound = "vờ",
                            UpperCase = "V"
                        },
                        new
                        {
                            Id = new Guid("d1ea0000-0000-4000-8000-00000000001c"),
                            DisplayOrder = 28,
                            ExampleEmoji = "🚲",
                            ExampleWord = "xe đạp",
                            LowerCase = "x",
                            Name = "ích-xì",
                            Sound = "xờ",
                            UpperCase = "X"
                        },
                        new
                        {
                            Id = new Guid("d1ea0000-0000-4000-8000-00000000001d"),
                            DisplayOrder = 29,
                            ExampleEmoji = "❤️",
                            ExampleWord = "yêu",
                            LowerCase = "y",
                            Name = "i dài",
                            Sound = "i",
                            UpperCase = "Y"
                        });
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1ea0000-0000-4000-8000-000000000100"),
                            DisplayName = "Bé Demo",
                            Email = "demo@dlearning.vn",
                            PasswordHash = "pbkdf2-sha256$600000$zmz5Jrdt8HVqMz3413OHZQ==$6f+Gd25WENriwukIIkMp+VFRVxMvbzPNjZ+11YdJXPw=",
                            Username = "demo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
